package com.acme.center.platform.iam.interfaces.rest.resources;

import java.util.List;

/**
 * User resource.
 * <p>
 *     This class represents a user resource.
 *     It is used to expose user information to the outside world.
 * </p>
 * @param id the user id. The id is unique and generated by the system.
 * @param username the username. The username is unique and identifies the user.
 * @param roles the roles. A user can have multiple roles.
 */
public record UserResource(Long id, String username, List<String> roles) {
}
